export const metadata = {
  title: "QU Registration system",
  description: "Generated by Next.js",
};

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/studentDashboard.css";

import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
